name: fake-news
channels:
  - defaults
dependencies:
  - ipykernel=6.19.2
  - mypy=0.981
  - numpy=1.23.5
  - pandas=1.5.2
  - pandas-stubs=1.5.0 # dev only
  - pip=22.3.1
  - pytest=7.1.2
  - python=3.10.9
  - scikit-learn=1.2.0
  - pip:
      - clean-text==0.6.0 
      - wandb==0.13.10
